# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstation.proto\"\x0e\n\x0c\x45mptyRequest\"(\n\x15StationInspectRequest\x12\x0f\n\x07station\x18\x01 \x01(\t\"O\n\x12RecordTempsRequest\x12\x0f\n\x07station\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0c\n\x04tmin\x18\x03 \x01(\x05\x12\x0c\n\x04tmax\x18\x04 \x01(\x05\"!\n\x10RecordTempsReply\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"3\n\x12StationSchemaReply\x12\x0e\n\x06schema\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"/\n\x10StationNameReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\".\n\x0fStationMaxReply\x12\x0c\n\x04tmax\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xef\x01\n\x07Station\x12\x35\n\rStationSchema\x12\r.EmptyRequest\x1a\x13.StationSchemaReply\"\x00\x12:\n\x0bStationName\x12\x16.StationInspectRequest\x1a\x11.StationNameReply\"\x00\x12\x37\n\x0bRecordTemps\x12\x13.RecordTempsRequest\x1a\x11.RecordTempsReply\"\x00\x12\x38\n\nStationMax\x12\x16.StationInspectRequest\x1a\x10.StationMaxReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'station_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTYREQUEST']._serialized_start=17
  _globals['_EMPTYREQUEST']._serialized_end=31
  _globals['_STATIONINSPECTREQUEST']._serialized_start=33
  _globals['_STATIONINSPECTREQUEST']._serialized_end=73
  _globals['_RECORDTEMPSREQUEST']._serialized_start=75
  _globals['_RECORDTEMPSREQUEST']._serialized_end=154
  _globals['_RECORDTEMPSREPLY']._serialized_start=156
  _globals['_RECORDTEMPSREPLY']._serialized_end=189
  _globals['_STATIONSCHEMAREPLY']._serialized_start=191
  _globals['_STATIONSCHEMAREPLY']._serialized_end=242
  _globals['_STATIONNAMEREPLY']._serialized_start=244
  _globals['_STATIONNAMEREPLY']._serialized_end=291
  _globals['_STATIONMAXREPLY']._serialized_start=293
  _globals['_STATIONMAXREPLY']._serialized_end=339
  _globals['_STATION']._serialized_start=342
  _globals['_STATION']._serialized_end=581
# @@protoc_insertion_point(module_scope)
